# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OWF Learn / GeoJSON
pages:
- Home: index.md
- 'GeoJSON Specification':
  - 'Overview': 'specification/overview.md'
  - 'Comments': 'specification/comments.md'
  - 'Version': 'specification/version.md'
  - 'Metadata': 'specification/metadata.md'
  - 'File Size': 'specification/file-size.md'
  - 'Alternatives to GeoJSON': 'specification/alternatives.md'
- 'GeoJSON Examples':
  - 'Overview': 'examples/overview.md'
  - 'Time Series': 'examples/time-series.md'
  - 'Symbolization': 'examples/symbolization.md'
- 'Using GeoJSON with Software':
  - 'Overview': 'using-geojson/overview.md'
  - 'ArcGIS': 'using-geojson/arcgis.md'
  - 'GeoTools': 'using-geojson/geotools.md'
  - 'QGIS': 'using-geojson/qgis.md'
  - 'Leaflet': 'using-geojson/leaflet.md'
- 'Resources': resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
#theme: readthedocs
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-geojson
site_description:  'Open Water Foundation Learn GeoJSON'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
extra:
        extra_css: 'css/extra-material-theme.css'
